version: "3"
services:
  db:
    container_name: strapi_db
    restart: unless-stopped
    env_file: .env
    image: mysql:8
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./database/mysql.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/data:/var/lib/mysql
    ports:
      - "3306:3306"
